import type { AlertItem, LapSnapshot } from "./types";

export const session = {
  race: "APEX GRAND PRIX",
  track: "SUZUKA CIRCUIT",
  country: "JPN",
  currentLap: 42,
  totalLaps: 57,
  driver: "A. MORETTI",
  car: "RV-04",
};

export const demoLaps: LapSnapshot[] = [
  {
    lap: 31,
    timestamp: "14:22:06",
    lapTime: "1:41.802",
    lapTimeSeconds: 101.802,
    lapDelta: -0.4,
    sectors: ["32.410", "40.118", "29.274"],
    state: "CALM",
    stress: 24,
    confidence: 94,
    risk: 12,
    riskLevel: "LOW",
    trend: "STABLE",
    transcript: "Balance is good. We can keep this pace.",
    intent: "HANDLING_CONCERN",
    intentLabel: "PACE CONFIRMATION",
    reasons: ["Stable vocal baseline", "Lap performance holding steady"],
  },
  {
    lap: 32,
    timestamp: "14:23:49",
    lapTime: "1:41.911",
    lapTimeSeconds: 101.911,
    lapDelta: -0.2,
    sectors: ["32.442", "40.154", "29.315"],
    state: "CALM",
    stress: 27,
    confidence: 92,
    risk: 14,
    riskLevel: "LOW",
    trend: "STABLE",
    transcript: "Copy. Tyres are coming in nicely.",
    intent: "TYRE_COMPLAINT",
    intentLabel: "TYRE STATUS",
    reasons: ["No escalation detected", "Tyre feedback remains neutral"],
  },
  {
    lap: 33,
    timestamp: "14:25:32",
    lapTime: "1:42.105",
    lapTimeSeconds: 102.105,
    lapDelta: 0.1,
    sectors: ["32.510", "40.202", "29.393"],
    state: "FOCUSED",
    stress: 31,
    confidence: 91,
    risk: 19,
    riskLevel: "LOW",
    trend: "RISING",
    transcript: "Front is starting to wash a little in sector two.",
    intent: "GRIP_ISSUE",
    intentLabel: "GRIP ISSUE",
    reasons: ["First grip signal detected", "Stress trend beginning to rise"],
  },
  {
    lap: 34,
    timestamp: "14:27:15",
    lapTime: "1:42.210",
    lapTimeSeconds: 102.21,
    lapDelta: 0.2,
    sectors: ["32.558", "40.240", "29.412"],
    state: "FOCUSED",
    stress: 35,
    confidence: 90,
    risk: 23,
    riskLevel: "LOW",
    trend: "RISING",
    transcript: "Understood. Managing the entry now.",
    intent: "HANDLING_CONCERN",
    intentLabel: "HANDLING NOTE",
    reasons: ["Stress increasing gradually", "Driver remains task-focused"],
  },
  {
    lap: 35,
    timestamp: "14:28:58",
    lapTime: "1:42.438",
    lapTimeSeconds: 102.438,
    lapDelta: 0.4,
    sectors: ["32.625", "40.311", "29.502"],
    state: "FOCUSED",
    stress: 39,
    confidence: 89,
    risk: 28,
    riskLevel: "LOW",
    trend: "RISING",
    transcript: "Rear is moving around more on traction.",
    intent: "GRIP_ISSUE",
    intentLabel: "GRIP ISSUE",
    reasons: ["Repeated grip vocabulary", "Lap delta now positive"],
  },
  {
    lap: 36,
    timestamp: "14:30:41",
    lapTime: "1:42.682",
    lapTimeSeconds: 102.682,
    lapDelta: 0.6,
    sectors: ["32.712", "40.342", "29.628"],
    state: "FOCUSED",
    stress: 43,
    confidence: 89,
    risk: 32,
    riskLevel: "MODERATE",
    trend: "RISING",
    transcript: "The rear is sliding everywhere now.",
    intent: "GRIP_ISSUE",
    intentLabel: "GRIP ISSUE",
    reasons: ["Repeated grip complaint detected", "Lap time degrading by 0.6s"],
  },
  {
    lap: 37,
    timestamp: "14:32:24",
    lapTime: "1:42.944",
    lapTimeSeconds: 102.944,
    lapDelta: 0.9,
    sectors: ["32.779", "40.401", "29.764"],
    state: "STRESSED",
    stress: 49,
    confidence: 88,
    risk: 39,
    riskLevel: "MODERATE",
    trend: "RISING",
    transcript: "I am losing the car on exit of fourteen.",
    intent: "HANDLING_CONCERN",
    intentLabel: "HANDLING CONCERN",
    reasons: ["Stress crossed the warning threshold", "Handling concern repeated"],
  },
  {
    lap: 38,
    timestamp: "14:34:07",
    lapTime: "1:43.218",
    lapTimeSeconds: 103.218,
    lapDelta: 1.1,
    sectors: ["32.850", "40.468", "29.900"],
    state: "STRESSED",
    stress: 56,
    confidence: 88,
    risk: 47,
    riskLevel: "MODERATE",
    trend: "RISING",
    transcript: "The front tyres are fading. Need to manage them.",
    intent: "TYRE_COMPLAINT",
    intentLabel: "TYRE COMPLAINT",
    reasons: ["First tyre complaint in escalation window", "Stress increased 13% over 2 laps"],
  },
  {
    lap: 39,
    timestamp: "14:35:50",
    lapTime: "1:43.486",
    lapTimeSeconds: 103.486,
    lapDelta: 1.3,
    sectors: ["32.910", "40.560", "30.016"],
    state: "STRESSED",
    stress: 63,
    confidence: 87,
    risk: 56,
    riskLevel: "HIGH",
    trend: "RISING",
    transcript: "Why are we still on these tyres?",
    intent: "STRATEGY_FRUSTRATION",
    intentLabel: "STRATEGY FRUSTRATION",
    reasons: ["Strategy frustration detected", "Lap time degradation accelerating"],
  },
  {
    lap: 40,
    timestamp: "14:37:33",
    lapTime: "1:43.921",
    lapTimeSeconds: 103.921,
    lapDelta: 1.5,
    sectors: ["33.004", "40.624", "30.293"],
    state: "STRESSED",
    stress: 69,
    confidence: 87,
    risk: 65,
    riskLevel: "HIGH",
    trend: "RISING",
    transcript: "Rear tyres are completely gone.",
    intent: "TYRE_COMPLAINT",
    intentLabel: "TYRE COMPLAINT",
    reasons: ["Second tyre complaint in 2 laps", "Stress rapidly increasing"],
  },
  {
    lap: 41,
    timestamp: "14:39:16",
    lapTime: "1:44.382",
    lapTimeSeconds: 104.382,
    lapDelta: 1.7,
    sectors: ["33.112", "40.740", "30.530"],
    state: "STRESSED",
    stress: 74,
    confidence: 87,
    risk: 72,
    riskLevel: "HIGH",
    trend: "RISING",
    transcript: "I can't control the car through the esses.",
    intent: "HANDLING_CONCERN",
    intentLabel: "HANDLING CONCERN",
    reasons: ["Handling concern now performance-relevant", "Lap delta reached +1.7s"],
  },
  {
    lap: 42,
    timestamp: "14:40:59",
    lapTime: "1:43.821",
    lapTimeSeconds: 103.821,
    lapDelta: 1.8,
    sectors: ["33.020", "40.710", "30.091"],
    state: "CRITICAL",
    stress: 82,
    confidence: 87,
    risk: 78,
    riskLevel: "HIGH",
    trend: "RISING",
    transcript: "Rear tyres are completely gone. Box this lap.",
    intent: "TYRE_COMPLAINT",
    intentLabel: "TYRE COMPLAINT",
    reasons: ["Stress increased 29% over the last 3 laps", "Three tyre-related complaints detected", "Lap performance degraded by 2.1s"],
  },
];

export const alerts: AlertItem[] = [
  { level: "CRITICAL", title: "Driver control concern", detail: "Handling language detected in consecutive messages.", lap: 41, time: "14:39:16" },
  { level: "HIGH", title: "Tyre degradation pattern", detail: "Three tyre-related complaints in the last 5 laps.", lap: 42, time: "14:40:59" },
  { level: "MODERATE", title: "Performance trend shift", detail: "Lap delta has moved beyond the pace envelope.", lap: 38, time: "14:34:07" },
];

